# Generated by Django 4.0.3 on 2022-04-19 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70, verbose_name='Имя')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Почта')),
                ('client_login', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Логин')),
                ('client_password', models.CharField(max_length=30, verbose_name='Пароль')),
                ('tel_number', models.CharField(max_length=13, unique=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('e_email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('employees_password', models.CharField(max_length=30, verbose_name='Пароль')),
                ('experience', models.IntegerField(verbose_name='Стаж')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
                ('tel_number', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('position', models.CharField(choices=[('Admin', 'Администратор'), ('Chief', 'Начальник'), ('Detective', 'Детектив'), ('Assistant', 'Помощник детектива'), ('Manager', 'Менеджер')], max_length=30, verbose_name='Должность')),
                ('status', models.CharField(choices=[('Busy', 'Занят'), ('Available', 'Свободен')], max_length=30, verbose_name='Статус сотрудника')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='TypeOfOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Наблюдение', 'Наблюдение'), ('Сбор информации', 'Сбор информации'), ('Розыск человека', 'Розыск человека')], max_length=50, unique=True, verbose_name='Тип заказа')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('expected_days', models.IntegerField(verbose_name='Ожидаемое количество дней')),
            ],
            options={
                'verbose_name': 'Тип заказа',
                'verbose_name_plural': 'Типы заказов',
                'db_table': 'type_of_order',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_comment', models.TextField(default='', max_length=500, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateField(default=2022, null=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('Closed', 'Закрыта'), ('In process', 'На рассмотрении менеджера'), ('Payed', 'Оплачена'), ('Rejected by client', 'Отклонена клиентом'), ('Rejected by manager', 'Отклонена менеджером'), ('In work', 'В работе')], default='In process', max_length=50, null=True, verbose_name='Статус заказа')),
                ('rate', models.IntegerField(default=1, null=True, verbose_name='Рейтинг')),
                ('type_of_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testApp.typeoforder', verbose_name='Тип заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
            },
        ),
    ]
