# Generated by Django 4.0.3 on 2022-04-19 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_order_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_login',
            field=models.CharField(max_length=30, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.clients', verbose_name='Клиент'),
        ),
    ]
